### PR TITLE
Hello!

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello,

As you probably know, Emacs 16.56 isn't a microemacs in the usual sense.  Anyway, I'm curious about the "microemacsen" collection.  What is its purpose?

I have an early copy of Dave Conroy's MicroEmacs, version 30 from Feb 1986.  In case you want to add that too.

### CODE REVIEW

**Comment by timoc** [comment]
I have been using emacs, or something like it before i even knew that emacs
existed. The wordstar keybindings, the macros, all of it was in my muscle memory
before i ever conceived of the existence of a unix box, let alone played on one.

The addictive maddening genius of Emacs and Microemacs are that they do not
enforce any kind of workflow on you. They enable you to build workflow around
themselves. 

The more you lean into making it part of your workflow, the more you want it
everywhere you use a keyboard. Like any other drug - The first taste is always
free. Ask Linus Torvalds, he maintains his own too.

So, its part collection, part homage, part junkie twitch, part work in
progress. 

For a work in progress: I want to keep a copy of all the micro-emacs-alikes, so that
i have something to fall back to when emacs reaches the lisp singularity and
implodes, recursively.

If you have anything to contribute I'm happy to 'host'!

**Comment by larsbrinkhoff** [comment]
I'm looking into the early history of Emacs.  By "early" I mean something like 1978-1987.

These are my results so far: http://github.com/larsbrinkhoff/emacs-history

**Comment by timoc** [comment]
Ooh. That's nice. Want to join the party? if you want to put repo under the microemacsen banner :)

I'll have to poke around back home to find the older stuff. I seem to remember a tool called E or similar which was fom IBM that was emacslike and had a macro programming language.

**Comment by larsbrinkhoff** [comment]
Thanks, but for now, I'd rather have it stay where it is.  But I'd be happy to share my findings!

My copy of MicroEMACS is here: https://github.com/larsbrinkhoff/emacs-history/tree/sources/Dave%20Conroy

I also found one EMACS-11 by Fred Fish that runs on top of PDP-11 TECO.

**Comment by timoc** [comment]
I've just forked your repo for the moment. 
Hmm. Microemacs has a kind of spotted history - what with ["Perfect Writer"](https://en.wikipedia.org/wiki/Perfect_Writer), Jasspa, and other commercial variants. 
Have you considered the commercial emacs variants/compats such as Brief?

**Comment by larsbrinkhoff** [comment]
Right, MicroEMACS branched off in a zillion directions.  For now, I'm content to have a copy of the original version.

I do consider commercial variants, but I hadn't heard about Brief so far.

There are three emacs-like editors that piqued my interest recently:
- BTL Emacs for PDP-11 Unix, by Warren Montgomery from Bell Labs.
- CCA Emacs by Steve Zimmerman.
- PEN by Barach, Taenzer, and Wells, from BBN.

If you have any information on those, please let me know!

**Comment by timoc** [comment]
Not come across any of those. I'm mostly interested in microemacsen, because they are all over the place. The ~~tree~~ shrub  that is the microemacs codebase is withering on the vine. 
There is no real central place anywhere for any of the variants. That was my initial idea, that one place would foster some sharing rather than the fork-a-geddon that has diluted its use.

**Pull request closed without merging**
